name: pkgbuild

on:
  workflow_dispatch:
    inputs:
      force-update:
        description: 'update artifacts'
        required: false
        default: 'false'
  push:
    branches:
      - master
      - main

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pkgbuild:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        archlinux_arch: [aarch64, x86_64]
        include:
          - archlinux_arch: aarch64
            docker_arch: aarch64
          - archlinux_arch: x86_64
            docker_arch: amd64
    name: pkgbuild for ${{ matrix.archlinux_arch }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: pkgbuild
        id: pkgbuild
        uses: Manjaro-Sway/manjaro-package-action@main
        with:
          docker_arch: ${{ matrix.docker_arch }}
          archlinux_arch: ${{ matrix.archlinux_arch }}
          gpg_keyid: ${{ secrets.GPG_KEYID }}
          gpg_signing_key_base64: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          dispatch-token: ${{ secrets.DISPATCH }}
          force-update: ${{ github.event.inputs.force-update }}
